// surfaces/dashboard/src/lib/components/ui/spinner/spinner.svelte
<script lang="ts">
import type { ComponentProps } from "svelte";
import { Loader2Icon } from "$lib/icons";
import { cn } from "$lib/utils.js";

let { class: className, ...restProps }: ComponentProps<typeof Loader2Icon> = $props();
</script>

<Loader2Icon
	role="status"
	aria-label="Loading"
	class={cn("size-4 animate-spin", className)}
	{...restProps}
/>

// surfaces/dashboard/src/components/ui/spinner.tsx
import { Loader2Icon } from "@/components/mingcute-icons";

import { cn } from "@/lib/utils";

function Spinner({ className, ...props }: React.ComponentProps<"svg">) {
	return <Loader2Icon role="status" aria-label="Loading" className={cn("size-4 animate-spin", className)} {...props} />;
}

export { Spinner };
